name: corporate_threat_detection
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency injection
  get_it: ^8.2.0

  # JSON serialization
  freezed: ^2.4.3
  json_serializable: ^6.5.4
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # Format phone number or date input
  mask_text_input_formatter: ^2.9.0

  # Reduced animation effect when pressing buttons 
  scale_button: ^2.1.2

  # Path
  path_provider: ^2.1.5

  # For entry, exit, and other animations
  animate_do: ^4.2.0

  # Router
  go_router: ^16.1.0

  # REST APIf
  dio: ^5.8.0+1
  dio_retry_plus: ^2.0.8
  http_parser: ^4.1.2

  # Database
  sqflite: ^2.4.2

  # SVG
  flutter_svg: ^2.2.0

  # Toast
  fluttertoast: ^8.0.9

  # Internationalization
  intl: ^0.20.2
  intl_utils: ^2.8.5

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Downloads and caches images from the Internet. 
  cached_network_image: ^3.4.1

  # Add space (gap) between widgets
  gap: ^3.0.1

  # To get the app version
  package_info_plus: ^9.0.0

  # Automatically detect and input SMS code
  otp_autofill: ^4.1.0

  # Convenient input for entering PIN or SMS code
  pinput: ^5.0.1
  # Skeleton UI for loading elements (shimmer effect)
  shimmer: ^3.0.0

  # To open a phone number, link, or email
  url_launcher: ^6.3.2

  #custom Accordion
  animated_custom_dropdown: ^3.1.1

  # Network info plus
  network_info_plus: ^6.1.4

  #device id
  device_info_plus: ^11.5.0
  image_picker: ^1.2.0

  #permission handler
  permission_handler: ^12.0.1
  # Path
  path: ^1.9.1

  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_remote_config: ^6.0.1
  firebase_messaging: ^16.0.1

  # Flutter loclal notification
  flutter_local_notifications: ^19.4.2

  #Time zone
  timezone: ^0.10.1

  # Keyboard listner
  flutter_keyboard_visibility: ^6.0.0

  # Change icon app 
  flutter_launcher_icons: ^0.14.4
  # chuck
  chuck_interceptor: ^2.2.6

  # Vedie player
  better_player_plus: ^1.1.2
  # Web view
  webview_flutter: ^4.13.0

  vimeo_video_player: ^1.0.1

  bloc_concurrency: ^0.3.0
  webview_flutter_android: ^4.10.5
  webview_flutter_wkwebview: ^3.23.1
  # Video player
  video_player: ^2.10.0
  #lotties
  lottie: ^3.3.2
  # Record
  record: ^6.0.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^7.4.5
  build_runner: ^2.4.13
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
